title: Surasia's Random Stuff Blog
description: >- 
  Welcome to my blog! This site covers some research and reverse engineering
  projects that I'm working on. This ranges from decompilation and malware
  analysis to game modding.
baseurl: ""
url: ""
twitter_username: Surasia_
github_username:  Surasia
repository: Surasia/surasia.github.io
theme: null
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
        block:
            line_numbers: true

plugins:
  - jekyll-feed
  - jekyll-paginate-v2

sass:
  sass_dir: _sass
  style: expanded

pagination:
  enabled: true
  per_page: 3
  sort_field: 'date'
  sort_reverse: true

include: ['_pages', '_posts', 'assets/images']